version: '3'

services:
  cassandra:
    image: cassandra:4.1.3
    ports:
      - "9042:9042"
    volumes:
      - cassandradata:/data
  mongodb:
    image: mongo:7.0.0
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  redis:
    image: redis:7.2.0
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  mongodata:
  cassandradata:
  redisdata: