version: '3'

services:
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=password
    ports:
      - "6379:6379"
    command: redis-server --requirepass mysecretpassword

